"""update datetime col in Order and StadiumCourtDisable

Revision ID: 09533f34a857
Revises: 1c7635662047
Create Date: 2023-11-11 13:17:10.639399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09533f34a857'
down_revision = '1c7635662047'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('Order', 'datetime')
    op.add_column('StadiumCourtDisable', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('StadiumCourtDisable', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StadiumCourtDisable', sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('StadiumCourtDisable', 'date')
    op.add_column('Order', sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('Order', 'date')
    # ### end Alembic commands ###
