"""update table schema of Stadium and StadiumCourt and Team and User

Revision ID: 0d9cd3d1f829
Revises: 5dae55ceb665
Create Date: 2023-11-18 20:04:52.498863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9cd3d1f829'
down_revision = '5dae55ceb665'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Stadium', sa.Column('venue_name', sa.String(), nullable=False))
    op.add_column('Stadium', sa.Column('max_number_of_people', sa.Integer(), nullable=False))
    op.drop_column('StadiumCourt', 'max_number_of_people')
    op.add_column('Team', sa.Column('current_member_number', sa.Integer(), nullable=False))
    op.drop_column('Team', 'orig_member_number')
    op.drop_column('User', 'token1')
    op.drop_column('User', 'token2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('token2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('token1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Team', sa.Column('orig_member_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Team', 'current_member_number')
    op.add_column('StadiumCourt', sa.Column('max_number_of_people', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Stadium', 'max_number_of_people')
    op.drop_column('Stadium', 'venue_name')
    # ### end Alembic commands ###
