"""add is_enabled col for TABLE StadiumCourt and recover update from TABLE order

Revision ID: 19db0ebbcc29
Revises: 70094dc45cdd
Create Date: 2023-12-03 04:44:59.845815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19db0ebbcc29'
down_revision = '70094dc45cdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Order', 'stadium_court_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('Order_stadium_court_id_fkey', 'Order', type_='foreignkey')
    op.create_foreign_key(None, 'Order', 'StadiumCourt', ['stadium_court_id'], ['id'], ondelete='CASCADE')
    op.add_column('StadiumCourt', sa.Column('is_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StadiumCourt', 'is_enabled')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.create_foreign_key('Order_stadium_court_id_fkey', 'Order', 'StadiumCourt', ['stadium_court_id'], ['id'], ondelete='SET NULL')
    op.alter_column('Order', 'stadium_court_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
