"""delete table StadiumCourtDisable and add StadiumDisable

Revision ID: 5dae55ceb665
Revises: 09533f34a857
Create Date: 2023-11-12 09:17:02.452426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dae55ceb665'
down_revision = '09533f34a857'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StadiumDisable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stadium_id'], ['Stadium.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('StadiumCourtDisable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StadiumCourtDisable',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"StadiumCourtDisable_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('stadium_court_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stadium_court_id'], ['StadiumCourt.id'], name='StadiumCourtDisable_stadium_court_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='StadiumCourtDisable_pkey')
    )
    op.drop_table('StadiumDisable')
    # ### end Alembic commands ###
