"""add google_map_url column for TABLE Stadium

Revision ID: 69f66df7278b
Revises: f53d264809ee
Create Date: 2023-11-23 11:10:40.413636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f66df7278b'
down_revision = 'f53d264809ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Stadium', sa.Column('google_map_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Stadium', 'google_map_url')
    # ### end Alembic commands ###
