"""update stadium_court ondelete action to SET NULL for TABLE order

Revision ID: 70094dc45cdd
Revises: 69f66df7278b
Create Date: 2023-12-02 18:04:09.436499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70094dc45cdd'
down_revision = '69f66df7278b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Order', 'stadium_court_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('Order_stadium_court_id_fkey', 'Order', type_='foreignkey')
    op.create_foreign_key(None, 'Order', 'StadiumCourt', ['stadium_court_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.create_foreign_key('Order_stadium_court_id_fkey', 'Order', 'StadiumCourt', ['stadium_court_id'], ['id'], ondelete='CASCADE')
    op.alter_column('Order', 'stadium_court_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
